AWSTemplateFormatVersion: 2010-09-09
Description: |
  This is just a  try
Parameters:
  KeyName:
    Description: Select your keypair from list
    Type: AWS::EC2::KeyPair::KeyName  
  EmrahsVPC:
    Description: This is default VPC 
    Type: AWS::EC2::VPC::Id
  

Resources:
  EmrECSecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH and HTTP ports #required
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      VpcId: !Ref EmrahsVPC
   
 

  EmrPhoneDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "21"
      AllowMajorVersionUpgrade: True
    #  AssociatedRoles:
    #    - DBInstanceRole
      AutoMinorVersionUpgrade: true
      AvailabilityZone: us-east-1d
      BackupRetentionPeriod: 0
   #   CACertificateIdentifier: String
   #   CharacterSetName: String
   #   CopyTagsToSnapshot: Boolean
   #   DBClusterIdentifier: String
      DBInstanceClass: db.t2.micro #required
    #  DBInstanceIdentifier: String
      DBName: clarusway_phonebook
   #   DBParameterGroupName: String
    #  DBSecurityGroups:
     #   - String it doesnt been use anymore 
     # DBSnapshotIdentifier: String
     # DBSubnetGroupName: String
     # DeleteAutomatedBackups: Boolean zaten defaultu otomatik siliyor.
     # DeletionProtection: Boolean defaultu koruma yapmıyor.
     # Domain: String  Bu ne bilmiyorum.
     # DomainIAMRoleName: String bu ne bilmiyorum.
     # EnableCloudwatchLogsExports: bunu kullanmıyoruz log kayıdı için kullanılıyor.
      #  - String
     # EnableIAMDatabaseAuthentication: Boolean
     # EnablePerformanceInsights: Boolean
      Engine: MYSQL
      EngineVersion: 8.0.19
     # Iops: Integer
     # KmsKeyId: String
     # LicenseModel: String
      MasterUserPassword: Ankara_1
      MasterUsername: admin
      MaxAllocatedStorage: 22
      MonitoringInterval: 0
     # MonitoringRoleArn: String
      MultiAZ: false
     # OptionGroupName: String
     # PerformanceInsightsKMSKeyId: String
     # PerformanceInsightsRetentionPeriod: Integer
      Port: "3306"
     # PreferredBackupWindow: String
     # PreferredMaintenanceWindow: String
     # ProcessorFeatures:
      #  - ProcessorFeature
     # PromotionTier: Integer
      PubliclyAccessible: true
     # SourceDBInstanceIdentifier: String
     # SourceRegion: String
     # StorageEncrypted: Boolean
      StorageType: gp2 
      Tags:
       - Key: Name
         Value: Emrah Tagı
     # Timezone: String
     # UseDefaultProcessorFeatures: Boolean
     # VPCSecurityGroups:
      #  - String