AWSTemplateFormatVersion: 2010-09-09

Description: 
  this templates creates an EC2 instance with a SSH connection. 

Resources:
  EmrahCFIInstance:
    Type: AWS::EC2::Instance
    Properties:

      ImageId: ami-0533f2ba8a1995cf9 

      InstanceType: t2.micro   

      KeyName: Firstkey

      SecurityGroups:
        - SSHandHTTP

      Tags:
        - Key: Name
          Value: Emrah cfc-instance